---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dvp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dvp
    spec:
      imagePullSecrets:
        - name: registry
      containers:
      - name: server
        image: registry.nextagilesoftdev.com/dviejo/gt-new/node-dev1
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 3000
        - name: remote-debug
          containerPort: 3001
        env:
          # Define the environment variable
          - name: SPECIAL_LEVEL_KEY
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                name: special-config
                # Specify the key associated with the value
                key: special.how
